project:
  type: website
  output-dir: docs

website:
  title: "Kiran Favre"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
      

format:
  html:
    theme: 
      - mystyles.scss
    #css: styles.css
    toc: true

editor: visual

