project:
  type: website
  output-dir: docs

website:
  title: "Kiran Favre"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
      - href: site_resume.pdf
        text: Resume
  page-footer: 
    left: 
      - "Copyright 2023, Kiran Favre"
    
    
      

format:
  html:
    theme: 
      - mystyles.scss
    css: styles.css
    toc: true

editor: visual

