{
  "hash": "7c3582986be712439f798dd65c1b941e",
  "result": {
    "markdown": "---\ntitle: \"Understanding the Relationship Between Temperature & Forest Area Burned\"\ndescription: Using a linear regression model to evaluate the relationship between temperature and hectares of forest burned. \neditor: visual\nauthor:\n  - name: Kiran Favre\n    url: https://kiranfavre.github.io\n    affiliation: Master of Environmental Data Science\n    affiliation-url: https://ucsb-meds.github.io/\ndate: 05-08-2023\ncitation: \n  url: https://kiranfavre.github.io/posts/2023-05-08_fire_linreg/ \ncategories: [Statistics, R]\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show code\"\nimage: IMG_4448.jpg\n---\n\n\n## Introduction\n\nIn this blog, I want to evaluate whether weather has an influence on forest fires. I have wondered about this considering the wildfires in [my region in 2020](https://en.wikipedia.org/wiki/CZU_Lightning_Complex_fires)).\n\n## Data\n\nThe data I will be using is a data set of daily forest fire area burned in the northeast region of Portugal and meteorological conditions on the recorded day (data was constructed from [here](http://www3.dsi.uminho.pt/pcortez/forestfires/)).\n\n## Exploration\n\n### Visualizing the data\n\nTo begin to understand this relationship, I will make a scatter plot showing area burned as it relates to temperature to determine the general relationship.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.2     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\nhere() starts at C:/Users/kiran/Documents/MEDS 2022-2023/kiranfavre.github.io\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nforestfires_data <- readRDS(\"~/MEDS 2022-2023/kiranfavre.github.io/posts/2023-05-08_fire_linreg/forestfires.rds\")\n\nggplot(forestfires_data,\n       aes(x = temp,\n           y = area)) +\n  geom_point(col = \"purple\") +\n  labs(x = \"Temperature (degrees Celsius)\",\n       y = \"Daily Forest Fire Area Burned (hectares)\",\n       title = \"Temperature vs. Daily Forest Fire Area Burned\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nHere I see a moderate positive correlation, which intuitively makes sense to me. If temperature is higher, fires that may not have continued to burn may keep burning for longer, covering a larger area. The correlation is not very strong, but I would say there is a positive correlation nonetheless.\n\n### Estimating the relationship with simple linear regression\n\nUsing the `lm()` command to estimate the following simple linear regression:\n\n$$ \\text{area_burned}_i = \\beta_0 + \\beta_1 \\text{temp}_i + \\varepsilon_i $$\n\nUsing this relationship, I will look into:\n\n-   How many hectares are predicted to burn on a day that is 1 degrees Celsius?\n\n-   How many hectares are predicted to burn on a day that is 28 degrees Celsius?\n\n-   How many more hectares are predicted to burn on a day in winter at 12 degrees Celsius as compared to a hot summer day at 30 degrees Celsius?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinreg <- lm(area ~ temp, data = forestfires_data) |> \n  summary() |> #summarize\n  xtable() |> #beautify\n  kable() \n\nprint(linreg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\n|            | Estimate| Std. Error|    t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|----------:|------------------:|\n|(Intercept) | 14.77689| 17.1649949|  0.8608733|          0.3897084|\n|temp        | 12.25678|  0.8686797| 14.1096681|          0.0000000|\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#one degree celsius day\narea_1C <- 14.77689 + 12.2578\narea_1C\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 27.03469\n```\n:::\n\n```{.r .cell-code}\n#28 degrees Celsius\narea_28C <- 14.77689 + (12.2578 * 28)\narea_28C\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 357.9953\n```\n:::\n\n```{.r .cell-code}\n#how many more hectares will be burned at 30 degrees vs 12\narea_diff <- (14.77689 + (12.2578 * 30)) - (14.77689 + (12.2578 * 12))\narea_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 220.6404\n```\n:::\n:::\n\n\nThis model predicts that at zero degrees temperature, there would be 14.78 hectares of burned area, and that for a one degree increase in temperature, the burn area will increase by 12.26 hectares. On a day that is one degree Celsius, this model predicts that there will be 27.03 hectares of burned area. On a 28 degrees Celsius day, the model predicts that 358 hectares of forest would be burned. This model predicts that there will be 220.6 more hectares burned on a 30 degree day than a 12 degree day.\n\n### Model fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = forestfires_data,\n       aes(temp, area)) +\n  geom_smooth(se = FALSE,\n              col = \"red\") +\n  geom_point(col = \"blue\",\n             alpha = 0.25) +\n  labs(x = \"Temperature (degrees Celsius)\",\n       y = \"Daily Forest Fire Area Burned (hectares)\",\n       title = \"Temperature vs. Daily Forest Fire Area Burned\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nI think the model is moderately accurate at fitting the data - it does accurately predict the moderate positive correlation that I saw from the scatter plot. The points are not super tight/close to the line but are also not very far (moderate residuals), and there are not many outliers except for at very high temperatures.\n\n### Coefficient of Determination\n\nThe coefficient of determination is the percentage of variance in y that is explained by x (and any other independent variables). Therefore, computing the coefficient of determination ($R^2$) will allow me to predict what percent of variation in area burned are explained by temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#need to do the regression without the table making\nregression <- lm(area ~ temp, data = forestfires_data)\n\nR2 = summary(regression)$r.squared\nprint(R2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2787951\n```\n:::\n:::\n\n\nApproximately 28% of variation in daily forest fire area burned in hectares can be attributed to a change in temperature. This does align with my intuition that the model is a moderate fit for this relationship. This coefficient of determination accounts for the positive correlation that I noticed and seems to account for some of the higher residuals in the middle to high values of temperature.\n\n### Omitted Variable Bias\n\nDue to complex climatological phenomena, days with high temperatures tend to coincide with days that are also different in other dimensions. For example, hot days tend to be less rainy, with lower wind, and of higher or lower humidity, depending on the geographic location. This raises the concern of **omitted variables bias**, as these variables may also be correlated with area burned.\n\nTo address this, I will add relative humidity (`RH`) as an independent variable to my linear regression model, in addition to temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRH_linreg <- lm(area ~ temp + RH, data =forestfires_data) |> \n  summary() |> \n  xtable() |> \n  kable() \n\nprint(RH_linreg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\n|            |    Estimate| Std. Error|   t value| Pr(>&#124;t&#124;)|\n|:-----------|-----------:|----------:|---------:|------------------:|\n|(Intercept) | -15.5334175| 31.3949740| -0.494774|          0.6209711|\n|temp        |  12.8782466|  1.0221028| 12.599756|          0.0000000|\n|RH          |   0.4193295|  0.3637187|  1.152895|          0.2494893|\n```\n:::\n:::\n\n\nAdding relative humidity to thie model changed the intercept drastically, but the coefficient on temperature did not change much. For every one degree Celsius increase, keeping relative humidity constant, the burn are will increase by 12.88 hectares. In this model without relative humidity, the slope coefficient was 12.26, so an increase of 0.62 acres is not enough to convince me that there is an omitted variable bias. Adding in relative humidity does not increase burned area greatly, which it would if this was a case of omitted variable bias.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}